name: Get artifacts from job                                                    

on: push

jobs: 
  upload-artifact:                                                              
    runs-on: ubuntu-latest
    steps:                                                                      
      - run: |
          echo "\`github\` context: $CONTEXT"
        env:
          CONTEXT: ${{ toJSON(github) }}
      - run: |
          echo "\`env\` context: $CONTEXT"
        env:
          CONTEXT: ${{ toJSON(env) }}
      - run: |
          echo "\`jobs\` context: $CONTEXT"
        env:
          CONTEXT: ${{ toJSON(job) }}
      - run: |
          echo "\`steps\` context: $CONTEXT"
        env:
          CONTEXT: ${{ toJSON(steps) }}
      - name: output all env vars
        run: |
          env
      - run: |
          echo "Hello, I'm a test artifact" >> artifact                      
      - uses: actions/upload-artifact@v3                                        
        with:                                                                   
          name: artifact 
          path: artifact
  gh-run-download-artifact:
    runs-on: ubuntu-latest
    needs: [ upload-artifact ]
    steps:
      - run: |
          gh run download --repo "${{ github.repository}}" --name artifact --dir . "${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                             
  download-artifact:                                                            
    runs-on: ubuntu-latest
    needs: [ upload-artifact ]
    steps:
      - uses: actions/download-artifact@v3                                      
        with:
          path: .                                                               
          name: artifact
